# =============================================================================
#  dlcore.pri -- THE list of DLConsole's shared sources (session 87)
#  ---------------------------------------------------------------------------
#  Compiled ONCE, into the static library `dlcore` (core/core.pro). The app
#  (app/app.pro), the unit tests (tests/tests.pro), the menu audit, the
#  screenshot harness and the find benchmark all link that library instead
#  of compiling these files again each; they include dlcore_link.pri.
#
#  Adding a source file: add it HERE, and only here.
#  Resources (.qrc) are NOT in the library -- see dlcore_link.pri.
# =============================================================================
INCLUDEPATH += $$PWD $$PWD/schema

SOURCES += \
    $$PWD/capturedecoder.cpp \
    $$PWD/crypto/aes128.cpp \
    $$PWD/crypto/kavachmac.cpp \
    $$PWD/schema/schemaencoder.cpp \
    $$PWD/packetbuilder.cpp \
    $$PWD/udpsender.cpp \
    $$PWD/packetmakerdialog.cpp \
    $$PWD/packetvariation.cpp \
    $$PWD/packetpreset.cpp \
    $$PWD/packetsequencedialog.cpp \
    $$PWD/subpacketwindow.cpp \
    $$PWD/dlrplayer.cpp \
    $$PWD/dlrplayerdialog.cpp \
    $$PWD/messageheader.cpp \
    $$PWD/sessionkeygen.cpp \
    $$PWD/sessionkeydialog.cpp \
    $$PWD/sessionkeystore.cpp \
    $$PWD/schema/schemadecoder.cpp \
    $$PWD/colorrules.cpp \
    $$PWD/comparewindow.cpp \
    $$PWD/constants.cpp \
    $$PWD/exportdialog.cpp \
    $$PWD/exporter.cpp \
    $$PWD/filterbar.cpp \
    $$PWD/findbar.cpp \
    $$PWD/gototimestampdialog.cpp \
    $$PWD/lococonsolewindow.cpp \
    $$PWD/tablefindbar.cpp \
    $$PWD/minimizeddock.cpp \
    $$PWD/textzoom.cpp \
    $$PWD/presentationmode.cpp \
    $$PWD/tabtags.cpp \
    $$PWD/tabpopoutwindow.cpp \
    $$PWD/livefields.cpp \
    $$PWD/bignumberpanel.cpp \
    $$PWD/statuspins.cpp \
    $$PWD/replaywindow.cpp \
    $$PWD/decodeworkbench.cpp \
    $$PWD/fieldsweep.cpp \
    $$PWD/fieldsweepdialog.cpp \
    $$PWD/framediff.cpp \
    $$PWD/framediffwindow.cpp \
    $$PWD/faultpanelwindow.cpp \
    $$PWD/brakingcurves.cpp \
    $$PWD/brakingcurveplot.cpp \
    $$PWD/brakingpanel.cpp \
    $$PWD/fieldindexdialog.cpp \
    $$PWD/logmodel.cpp \
    $$PWD/logtableview.cpp \
    $$PWD/logtimedelegate.cpp \
    $$PWD/locoidentity.cpp \
    $$PWD/rejectrules.cpp \
    $$PWD/logwriter.cpp \
    $$PWD/mainwindow.cpp \
    $$PWD/profileiodialogs.cpp \
    $$PWD/mainwindow_menus.cpp \
    $$PWD/mainwindow_status.cpp \
    $$PWD/mainwindow_tabs.cpp \
    $$PWD/mainwindow_tools.cpp \
    $$PWD/mainwindow_shell.cpp \
    $$PWD/mainwindowsession.cpp \
    $$PWD/messagedispatcher.cpp \
    $$PWD/undolog.cpp \
    $$PWD/cabpanel.cpp \
    $$PWD/dmipanel.cpp \
    $$PWD/dmitimetravel.cpp \
    $$PWD/speeddistance.cpp \
    $$PWD/clockskewalarm.cpp \
    $$PWD/runreport.cpp \
    $$PWD/runreportwindow.cpp \
    $$PWD/incidentreport.cpp \
    $$PWD/incidentreportdialog.cpp \
    $$PWD/incidentreportwindow.cpp \
    $$PWD/twolocoview.cpp \
    $$PWD/twolocowindow.cpp \
    $$PWD/trackdiagram.cpp \
    $$PWD/trackdiagramwindow.cpp \
    $$PWD/workspacesnapshot.cpp \
    $$PWD/settingsbundle.cpp \
    $$PWD/namemap.cpp \
    $$PWD/rawbytespanel.cpp \
    $$PWD/bookmarks.cpp \
    $$PWD/archivesearch.cpp \
    $$PWD/commandpalette.cpp \
    $$PWD/archivesearchwindow.cpp \
    $$PWD/fieldcatalog.cpp \
    $$PWD/fieldindex.cpp \
    $$PWD/fieldinspector.cpp \
    $$PWD/fieldplot.cpp \
    $$PWD/logentry.cpp \
    $$PWD/keyblock.cpp \
    $$PWD/logquery.cpp \
    $$PWD/queryhistory.cpp \
    $$PWD/querylineedit.cpp \
    $$PWD/windowgeometry.cpp \
    $$PWD/markerscrollbar.cpp \
    $$PWD/mergedwindow.cpp \
    $$PWD/notificationcenter.cpp \
    $$PWD/timelineribbon.cpp \
    $$PWD/roundtrip.cpp \
    $$PWD/roundtripwindow.cpp \
    $$PWD/emptystate.cpp \
    $$PWD/watchpanel.cpp \
    $$PWD/watchlist.cpp \
    $$PWD/pinboard.cpp \
    $$PWD/pinpanel.cpp \
    $$PWD/frameclock.cpp \
    $$PWD/framenumberwatch.cpp \
    $$PWD/savedata.cpp \
    $$PWD/statusline.cpp \
    $$PWD/uicolors.cpp \
    $$PWD/uistyle.cpp \
    $$PWD/searchwindow.cpp \
    $$PWD/sessionreader.cpp \
    $$PWD/testassertions.cpp \
    $$PWD/stickymenu.cpp \
    $$PWD/sessionwindow.cpp \
    $$PWD/settingsdialog.cpp \
    $$PWD/udpcommunication.cpp

HEADERS += \
    $$PWD/Constants.h \
    $$PWD/capturedecoder.h \
    $$PWD/crypto/aes128.h \
    $$PWD/crypto/kavachmac.h \
    $$PWD/schema/schemaencoder.h \
    $$PWD/packetbuilder.h \
    $$PWD/udpsender.h \
    $$PWD/packetmakerdialog.h \
    $$PWD/packetvariation.h \
    $$PWD/packetpreset.h \
    $$PWD/packetsequencedialog.h \
    $$PWD/subpacketwindow.h \
    $$PWD/dlrplayer.h \
    $$PWD/dlrplayerdialog.h \
    $$PWD/messageheader.h \
    $$PWD/sessionkeygen.h \
    $$PWD/sessionkeydialog.h \
    $$PWD/sessionkeystore.h \
    $$PWD/schema/schemadecoder.h \
    $$PWD/IRS.h \
    $$PWD/Structures.h \
    $$PWD/colorrules.h \
    $$PWD/comparewindow.h \
    $$PWD/exportdialog.h \
    $$PWD/exporter.h \
    $$PWD/filterbar.h \
    $$PWD/findbar.h \
    $$PWD/gototimestampdialog.h \
    $$PWD/lococonsolewindow.h \
    $$PWD/tablefindbar.h \
    $$PWD/minimizeddock.h \
    $$PWD/textzoom.h \
    $$PWD/presentationmode.h \
    $$PWD/tabtags.h \
    $$PWD/tabpopoutwindow.h \
    $$PWD/livefields.h \
    $$PWD/bignumberpanel.h \
    $$PWD/statuspins.h \
    $$PWD/replaywindow.h \
    $$PWD/decodeworkbench.h \
    $$PWD/fieldsweep.h \
    $$PWD/fieldsweepdialog.h \
    $$PWD/framediff.h \
    $$PWD/framediffwindow.h \
    $$PWD/faultpanelwindow.h \
    $$PWD/brakingcurves.h \
    $$PWD/brakingcurveplot.h \
    $$PWD/brakingpanel.h \
    $$PWD/logentry.h \
    $$PWD/fieldindexdialog.h \
    $$PWD/logmodel.h \
    $$PWD/logtableview.h \
    $$PWD/logtimedelegate.h \
    $$PWD/locoidentity.h \
    $$PWD/rejectrules.h \
    $$PWD/logwriter.h \
    $$PWD/mainwindow.h \
    $$PWD/profileio.h \
    $$PWD/profileiodialogs.h \
    $$PWD/messagedispatcher.h \
    $$PWD/undolog.h \
    $$PWD/cabpanel.h \
    $$PWD/dmipanel.h \
    $$PWD/dmitimetravel.h \
    $$PWD/speeddistance.h \
    $$PWD/clockskewalarm.h \
    $$PWD/runreport.h \
    $$PWD/runreportwindow.h \
    $$PWD/incidentreport.h \
    $$PWD/incidentreportdialog.h \
    $$PWD/incidentreportwindow.h \
    $$PWD/twolocoview.h \
    $$PWD/twolocowindow.h \
    $$PWD/trackdiagram.h \
    $$PWD/trackdiagramwindow.h \
    $$PWD/workspacesnapshot.h \
    $$PWD/settingsbundle.h \
    $$PWD/namemap.h \
    $$PWD/rawbytespanel.h \
    $$PWD/bookmarks.h \
    $$PWD/archivesearch.h \
    $$PWD/commandpalette.h \
    $$PWD/archivesearchwindow.h \
    $$PWD/fieldcatalog.h \
    $$PWD/fieldindex.h \
    $$PWD/fieldinspector.h \
    $$PWD/fieldplot.h \
    $$PWD/keyblock.h \
    $$PWD/logquery.h \
    $$PWD/queryhistory.h \
    $$PWD/querylineedit.h \
    $$PWD/windowgeometry.h \
    $$PWD/markerscrollbar.h \
    $$PWD/mergedwindow.h \
    $$PWD/notificationcenter.h \
    $$PWD/timelineribbon.h \
    $$PWD/roundtrip.h \
    $$PWD/roundtripwindow.h \
    $$PWD/emptystate.h \
    $$PWD/watchpanel.h \
    $$PWD/watchlist.h \
    $$PWD/pinboard.h \
    $$PWD/pinpanel.h \
    $$PWD/frameclock.h \
    $$PWD/framenumberwatch.h \
    $$PWD/savedata.h \
    $$PWD/statusline.h \
    $$PWD/sendguard.h \
    $$PWD/uicolors.h \
    $$PWD/uistyle.h \
    $$PWD/searchwindow.h \
    $$PWD/sessionfile.h \
    $$PWD/sessionreader.h \
    $$PWD/testassertions.h \
    $$PWD/stickymenu.h \
    $$PWD/sessionwindow.h \
    $$PWD/settings.h \
    $$PWD/settingsdialog.h \
    $$PWD/theme.h \
    $$PWD/udpcommunication.h

FORMS += \
    $$PWD/mainwindow.ui

include($$PWD/flasher/flasher.pri)
include($$PWD/lococonfig/lococonfig.pri)
include($$PWD/serial.pri)
