#include "testutil.h"

#include "lococonfigcore.h"
#include "lococonfighistorydialog.h"
#include "lococonfigmodel.h"
#include "lococonfigwindow.h"

#include <QCoreApplication>
#include <QDir>
#include <QElapsedTimer>
#include <QFile>
#include <QHostAddress>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QtEndian>
#include <QSet>
#include <QTemporaryDir>
#include <QUdpSocket>
#include <QPushButton>

#include <cmath>

// =============================================================================
//  Loco Configuration (LOCO_INFO editor and sender).
//
//  The anchor is tests/fixtures/loco_info_default.bin, GENERATED by
//  lococonfig/sync_linfo.py from the loco_config tool: the body the tool
//  itself writes with its own values, after the script has checked every
//  kavach.xml LINFO field against the C struct (offsetof / sizeof).
//  lococonfig/loco_defaults.json comes from the same run. Packing those
//  defaults with the layout read from kavach.xml must give the fixture
//  byte for byte.
//
//  Nothing here hard-codes the struct's size, member count or CRC: adding a
//  LOCO_INFO member is one <field> line in kavach.xml plus a sync_linfo.py
//  run (lococonfig/ADDING_A_FIELD.md), and these tests follow. Stale
//  generated files fail with a message that says to re-run the script.
//
//  Suites:
//    lococonfig     layout, packing, CRC, text formats, validation, the
//                   presentation file, the store, the history
//    lococonfigrun  the real window: edit, reject a bad edit, send to a
//                   UDP socket on 127.0.0.1, check the datagram byte for
//                   byte, the history record and what survives a reopen
// =============================================================================

namespace {

QByteArray readFixture()
{
    QFile file(QStringLiteral(DL_SRC_DIR) + QStringLiteral("/tests/fixtures/loco_info_default.bin"));
    if (!file.open(QIODevice::ReadOnly)) {
        return QByteArray();
    }
    return file.readAll();
}

bool loadAll(LocoInfo::Layout *layout, LocoInfo::Presentation *presentation, LocoInfo::Values *defaults)
{
    QString error;
    if (!layout->load(QStringLiteral(":/schema/kavach.xml"), &error)) {
        return false;
    }
    *presentation = LocoInfo::Presentation::fromLayout(*layout);
    return LocoInfo::loadDefaults(QStringLiteral(":/lococonfig/loco_defaults.json"), *layout, defaults, &error);
}

}  // namespace

// =============================================================================
TEST_SUITE(lococonfig)
{
    LocoInfo::Layout layout;
    LocoInfo::Presentation presentation;
    LocoInfo::Values defaults;
    CHECK(loadAll(&layout, &presentation, &defaults), "layout, presentation and defaults load");
    if (!layout.isLoaded()) {
        return;
    }

    // ---- layout from the schema --------------------------------------------------
    CHECK(layout.crcField() && layout.crcField()->key == QStringLiteral("loco_info_crc")
              && layout.crcField()->offset == layout.bodySize() - 4,
          "loco_info_crc is the last u32, a top-level member");
    CHECK(layout.field(QStringLiteral("speed_margin_eb")) && layout.field(QStringLiteral("national_values.speed_margin_eb")),
          "the two speed_margin_eb are told apart by their section");
    CHECK(layout.field(QStringLiteral("static_brake_params.train_desc"))
              && layout.field(QStringLiteral("static_brake_params.train_desc"))->kind == LocoInfo::Kind::Char
              && layout.field(QStringLiteral("static_brake_params.train_desc"))->size == 40,
          "train_desc is char[40]");
    CHECK(layout.field(QStringLiteral("braking_prints")) != nullptr,
          "braking_prints is back at the top level, after the nested structs, as in the C struct");
    CHECK(layout.field(QStringLiteral("mr_pressure"))->kind == LocoInfo::Kind::Float, "pressures are f32");
    CHECK(layout.field(QStringLiteral("vcc_crc"))->hex, "vcc_crc displays as hex (schema hexup)");

    // ---- golden: the tool's own bytes ------------------------------------------------
    const QByteArray golden = readFixture();
    CHECK(golden.size() == layout.bodySize(),
          QStringLiteral("the fixture is %1 bytes and the schema's LINFO %2: run "
                         "python3 lococonfig/sync_linfo.py <loco_config.cpp>")
              .arg(golden.size()).arg(layout.bodySize()).toUtf8().constData());
    {
        QFile file(QStringLiteral(":/lococonfig/loco_defaults.json"));
        file.open(QIODevice::ReadOnly);
        const int recorded = QJsonDocument::fromJson(file.readAll()).object().value(QStringLiteral("body_bytes")).toInt();
        CHECK(recorded == layout.bodySize(),
              "loco_defaults.json was generated for this layout (else re-run sync_linfo.py)");
    }
    const QByteArray packed = LocoInfo::encodeBody(layout, defaults);
    CHECK(packed == golden, "packing the defaults gives the tool's loco_info.bin byte for byte");
    CHECK(golden.size() >= 4 && LocoInfo::crc32(packed.left(layout.bodySize() - 4))
                                 == qFromLittleEndian<quint32>(golden.constData() + layout.bodySize() - 4),
          "loco_info_crc matches the tool's");
    {
        const LocoInfo::Field &desc = *layout.field(QStringLiteral("static_brake_params.train_desc"));
        const QByteArray text = packed.mid(desc.offset, desc.size);
        const int terminator = text.indexOf('\0');
        CHECK(terminator >= 0 && text.mid(terminator) == QByteArray(desc.size - terminator, '\0'),
              "train_desc is zero after its NUL -- no leftover memory inside the CRC");
    }

    const LocoInfo::Parsed parsed = LocoInfo::parseBody(layout, golden);
    CHECK(parsed.ok && parsed.crcOk, "the golden body parses, CRC good");
    CHECK(LocoInfo::changedKeys(layout, defaults, parsed.values).isEmpty(), "and reads back as the defaults");
    CHECK(LocoInfo::encodeBody(layout, parsed.values) == golden, "parse → pack is byte-identical");
    CHECK(parsed.values.value(QStringLiteral("gsm_1_apn_name")).toString() == QStringLiteral("ABCD"),
          "char arrays read up to their NUL");
    CHECK(LocoInfo::formatValue(*layout.field(QStringLiteral("nsb_pressure")),
                                parsed.values.value(QStringLiteral("nsb_pressure"))) == QStringLiteral("4.2"),
          "4.2f shows as 4.2");

    // ---- the datagram ------------------------------------------------------------------
    const QByteArray datagram = LocoInfo::message(golden);
    CHECK(datagram.size() == layout.bodySize() + 5, "header + body, sizeof(LOCO_INFO)");
    CHECK(datagram.left(3) == QByteArray::fromHex("1c0278")
              && qFromLittleEndian<quint16>(datagram.constData() + 3) == datagram.size(),
          "header: src 28, dest 2, msg 120, then the whole length little-endian");
    CHECK(LocoInfo::parseBody(layout, datagram).ok, "the datagram form parses too (header stripped)");

    QByteArray damaged = golden;
    damaged[10] = static_cast<char>(damaged[10] ^ 0x01);
    const LocoInfo::Parsed damagedParse = LocoInfo::parseBody(layout, damaged);
    CHECK(damagedParse.ok && !damagedParse.crcOk, "a flipped bit is caught by the CRC and reported");
    {
        const LocoInfo::Parsed shortFile = LocoInfo::parseBody(layout, golden.left(golden.size() - 1));
        CHECK(!shortFile.ok && shortFile.error.contains(QStringLiteral("different LOCO_INFO")),
              "a file of another size is refused as another LOCO_INFO version");
    }

    // ---- values: text in and out -------------------------------------------------------
    {
        const LocoInfo::Field &nms = *layout.field(QStringLiteral("nms_ip_address"));
        QVariant value;
        QString error;
        CHECK(LocoInfo::parseValueText(nms, QStringLiteral("127.0.0.1"), QStringLiteral("ipv4"), &value, &error)
                  && value.toLongLong() == 2130706433,
              "127.0.0.1 is 2130706433, as the tool writes it");
        CHECK(LocoInfo::formatValue(nms, static_cast<qint64>(2130706433), QStringLiteral("ipv4")) == QStringLiteral("127.0.0.1"),
              "and shows as 127.0.0.1");
        CHECK(!LocoInfo::parseValueText(nms, QStringLiteral("300.1.1.1"), QStringLiteral("ipv4"), &value, &error),
              "a bad address is refused");

        const LocoInfo::Field &u8 = *layout.field(QStringLiteral("loco_offset_front1"));
        CHECK(LocoInfo::parseValueText(u8, QStringLiteral("0x1F"), QString(), &value, &error) && value.toLongLong() == 31,
              "integers accept 0x hex");
        CHECK(!LocoInfo::parseValueText(u8, QStringLiteral("256"), QString(), &value, &error) && error.contains(QStringLiteral("0–255")),
              "a u8 over 255 is refused, with the range");
        CHECK(!LocoInfo::parseValueText(u8, QStringLiteral("-1"), QString(), &value, &error), "negative is refused");

        const LocoInfo::Field &u32 = *layout.field(QStringLiteral("loco_unit_id"));
        CHECK(LocoInfo::parseValueText(u32, QStringLiteral("4294967295"), QString(), &value, &error),
              "the full u32 range is accepted");
        CHECK(!LocoInfo::parseValueText(u32, QStringLiteral("4294967296"), QString(), &value, &error),
              "one past it is refused");

        const LocoInfo::Field &apn = *layout.field(QStringLiteral("gsm_1_apn_name"));
        CHECK(LocoInfo::parseValueText(apn, QString(39, QLatin1Char('a')), QString(), &value, &error),
              "39 characters fit in char[40]");
        CHECK(!LocoInfo::parseValueText(apn, QString(40, QLatin1Char('a')), QString(), &value, &error),
              "40 do not: there must be room for the NUL");
        CHECK(!LocoInfo::parseValueText(apn, QStringLiteral("apn\u00e9"), QString(), &value, &error),
              "non-ASCII is refused");

        const LocoInfo::Field &pressure = *layout.field(QStringLiteral("mr_pressure"));
        CHECK(!LocoInfo::parseValueText(pressure, QStringLiteral("nan"), QString(), &value, &error), "NaN is refused");
        CHECK(LocoInfo::sameValue(pressure, 4.2, 4.2000000001), "floats compare by their packed bytes");

        LocoInfo::Values bad = defaults;
        bad.insert(QStringLiteral("loco_max_speed"), static_cast<qint64>(70000));
        CHECK(LocoInfo::validate(layout, bad).size() == 1, "validate() finds the out-of-range u16");
        QString encodeError;
        CHECK(LocoInfo::encodeBody(layout, bad, &encodeError).isEmpty() && encodeError.contains(QStringLiteral("loco_max_speed")),
              "and encode refuses it rather than truncating");
    }

    // ---- the presentation comes from the schema's ui-* attributes ------------------------
    {
        CHECK(!presentation.groups.isEmpty() && presentation.groups.first().title == QStringLiteral("Loco & wheels"),
              "groups come from ui-group, in struct order");
        CHECK(presentation.groupOf(QStringLiteral("national_values.overlap")) == QStringLiteral("National values (UBA)"),
              "a nested member's group");
        CHECK(presentation.formats.value(QStringLiteral("kms_ip_address")) == QStringLiteral("ipv4"),
              "ui-format reaches the editor");
        CHECK(presentation.notes.value(QStringLiteral("vcc_crc")).contains(QStringLiteral("by hand")),
              "ui-note reaches the editor");
        CHECK(layout.field(QStringLiteral("init_state_machine_atf"))->cName == QStringLiteral("use_init_state_machine_atf"),
              "c-name maps a schema field to a differently named C member");
        CHECK(layout.field(QStringLiteral("loco_unit_id"))->cName == QStringLiteral("loco_unit_id"),
              "without c-name the C member has the schema's name");
    }

    // ---- the store ---------------------------------------------------------------------
    QTemporaryDir temp;
    CHECK(temp.isValid(), "a temporary directory");
    {
        const QString path = QDir(temp.path()).filePath(QStringLiteral("loco_configs.json"));
        LocoInfo::ConfigStore store(path, &layout, defaults);
        CHECK(store.load() && store.names().size() == 1, "no file: one configuration, from the defaults");
        CHECK(LocoInfo::changedKeys(layout, defaults, store.config(store.activeName()).values).isEmpty(),
              "with the default values");

        LocoInfo::LocoConfig loco;
        loco.name = QStringLiteral("WAP7 30421");
        loco.values = defaults;
        loco.values.insert(QStringLiteral("loco_unit_id"), static_cast<qint64>(30421));
        loco.values.insert(QStringLiteral("nsb_pressure"), 4.3);
        loco.values.insert(QStringLiteral("gsm_2_apn_name"), QStringLiteral("kavach.apn"));
        loco.targets[0].ip = QStringLiteral("10.1.2.3");
        loco.targets[0].port = 50011;
        loco.targets[1].ip = QStringLiteral("10.1.2.4");
        loco.targets[2].ip = QStringLiteral("10.1.2.5");
        loco.targets[2].enabled = false;
        loco.lastSentBody = LocoInfo::encodeBody(layout, loco.values);
        loco.lastSentAt = QDateTime::currentDateTimeUtc();
        loco.lastSentTarget = QStringLiteral("10.1.2.3:50011");
        store.upsert(loco);
        store.setActiveName(loco.name);
        CHECK(store.save(), "saves");

        LocoInfo::ConfigStore reread(path, &layout, defaults);
        CHECK(reread.load() && reread.names().size() == 2 && reread.activeName() == loco.name,
              "loads back both, active remembered");
        const LocoInfo::LocoConfig back = reread.config(loco.name);
        CHECK(LocoInfo::changedKeys(layout, loco.values, back.values).isEmpty(), "every value survives, floats and text included");
        CHECK(back.targets.size() == LocoInfo::kMaxTargets, "always four target rows");
        CHECK(back.targets[0].ip == QStringLiteral("10.1.2.3") && back.targets[0].port == 50011
                  && back.targets[1].ip == QStringLiteral("10.1.2.4")
                  && back.targets[2].ip == QStringLiteral("10.1.2.5") && !back.targets[2].enabled
                  && back.targets[3].ip.isEmpty(),
              "every target row survives: address, port, and whether it is ticked");
        CHECK(back.lastSentBody == loco.lastSentBody && back.lastSentAt.isValid(), "the last-sent bytes survive");
        CHECK(!reread.remove(QStringLiteral("nope")) && reread.remove(loco.name) && !reread.remove(reread.names().first()),
              "remove works, but never the last configuration");

        // A saved file from a schema that had one more member, and lacks one.
        QFile file(path);
        file.open(QIODevice::ReadOnly);
        QJsonObject root = QJsonDocument::fromJson(file.readAll()).object();
        file.close();
        QJsonArray configs = root.value(QStringLiteral("configs")).toArray();
        QJsonObject first = configs.at(1).toObject();
        QJsonObject values = first.value(QStringLiteral("values")).toObject();
        values.insert(QStringLiteral("retired_field"), 5);
        values.remove(QStringLiteral("frame_cycle"));
        first.insert(QStringLiteral("values"), values);
        configs.replace(1, first);
        root.insert(QStringLiteral("configs"), configs);
        file.open(QIODevice::WriteOnly | QIODevice::Truncate);
        file.write(QJsonDocument(root).toJson());
        file.close();
        LocoInfo::ConfigStore changed(path, &layout, defaults);
        changed.load();
        CHECK(changed.droppedKeys() == QStringList{ QStringLiteral("retired_field") },
              "a field the schema no longer has is dropped and reported");
        CHECK(changed.config(loco.name).values.value(QStringLiteral("frame_cycle")) == defaults.value(QStringLiteral("frame_cycle")),
              "a field the file lacks takes the default");
    }

    // ---- targets: files from before bulk send, and the rules ------------------------
    {
        // A configuration saved before bulk send: one target_ip / port.
        const QString path = QDir(temp.path()).filePath(QStringLiteral("old_configs.json"));
        QFile file(path);
        file.open(QIODevice::WriteOnly);
        file.write(R"({"format":1,"active":"Old","configs":[{"name":"Old","target_ip":"192.168.9.9","port":50021,"values":{}}]})");
        file.close();
        LocoInfo::ConfigStore old(path, &layout, defaults);
        CHECK(old.load(), "a pre-bulk-send file loads");
        const LocoInfo::LocoConfig oldConfig = old.config(QStringLiteral("Old"));
        CHECK(oldConfig.targets.size() == LocoInfo::kMaxTargets && oldConfig.targets[0].ip == QStringLiteral("192.168.9.9")
                  && oldConfig.targets[0].port == 50021 && oldConfig.targets[0].enabled
                  && oldConfig.targets[1].ip.isEmpty(),
              "its single target becomes row 1, the other rows empty");
        CHECK(old.save(), "and it saves");
        QFile saved(path);
        saved.open(QIODevice::ReadOnly);
        const QJsonObject savedConfig = QJsonDocument::fromJson(saved.readAll()).object()
                                            .value(QStringLiteral("configs")).toArray().first().toObject();
        CHECK(savedConfig.value(QStringLiteral("target_ip")).toString() == QStringLiteral("192.168.9.9"),
              "row 1 is still written under the old key, for an older DLConsole");

        QVector<LocoInfo::SendTarget> rows(LocoInfo::kMaxTargets);
        rows[0].ip.clear();
        CHECK(!LocoInfo::targetProblem(rows).isEmpty(), "no address anywhere: nothing to send to");
        rows[0].ip = QStringLiteral("10.0.0.1");
        CHECK(LocoInfo::targetProblem(rows).isEmpty(), "one address is enough");
        rows[1].ip = QStringLiteral("10.0.0.300");
        CHECK(LocoInfo::targetProblem(rows).contains(QStringLiteral("Target 2")), "a bad address is refused, by row");
        rows[1].enabled = false;
        CHECK(LocoInfo::targetProblem(rows).isEmpty(), "an unticked row is ignored, whatever is in it");
        rows[2].ip = QStringLiteral("10.0.0.1");
        CHECK(LocoInfo::targetProblem(rows).contains(QStringLiteral("twice")), "the same address and port twice is refused");
        rows[2].port = 50002;
        CHECK(LocoInfo::targetProblem(rows).isEmpty(), "same address, different port is fine");
        rows[0].enabled = false;
        rows[2].enabled = false;
        CHECK(!LocoInfo::targetProblem(rows).isEmpty(), "nothing ticked: nothing to send to");
    }

    // ---- the history ---------------------------------------------------------------------
    {
        LocoInfo::SendHistory history(QDir(temp.path()).filePath(QStringLiteral("history.jsonl")));
        LocoInfo::SendRecord record;
        record.when = QDateTime::currentDateTimeUtc();
        record.operatorName = QStringLiteral("abhinav");
        record.configName = QStringLiteral("WAP7 30421");
        record.target = QStringLiteral("10.1.2.3:50011");
        record.body = golden;
        record.crc = LocoInfo::crc32(golden.left(golden.size() - 4));
        record.vccCrc = 0xF6134AC1u;
        CHECK(history.append(record) && history.append(record), "two sends appended");
        QFile file(history.filePath());
        file.open(QIODevice::WriteOnly | QIODevice::Append);
        file.write("{\"when\":\"2026-09-25T10:");
        file.close();
        int skipped = 0;
        const QList<LocoInfo::SendRecord> all = history.readAll(&skipped);
        CHECK(all.size() == 2 && skipped == 1, "a torn last line costs that line only");
        CHECK(all.first().body == golden && all.first().vccCrc == 0xF6134AC1u, "the exact bytes and vcc_crc come back");

        LocoConfigHistoryDialog dialog(history.filePath(), &layout);
        CHECK(dialog.visibleRowCount() == 2, "the History dialog lists them");
    }
}

// =============================================================================
TEST_SUITE(lococonfigrun)
{
    QTemporaryDir temp;
    CHECK(temp.isValid(), "a temporary data directory");

    QUdpSocket vcc;
    CHECK(vcc.bind(QHostAddress(QHostAddress::LocalHost), 0), "a stand-in VCC socket on 127.0.0.1");

    QByteArray sentBody;
    {
        LocoConfigWindow window(nullptr, temp.path());
        CHECK(window.isUsable(), "the window loads the layout from the schema");
        window.setTarget(QStringLiteral("127.0.0.1"), vcc.localPort());

        LocoFieldModel *model = window.fieldModel();
        const int unitRow = model->rowForKey(QStringLiteral("loco_unit_id"));
        CHECK(model->setData(model->index(unitRow, LocoFieldModel::ColumnValue), QStringLiteral("30421"), Qt::EditRole),
              "loco_unit_id edited to 30421");
        CHECK(model->index(unitRow, 0).data(LocoFieldModel::ChangedFromDefaultRole).toBool(),
              "and marked as changed from the default");

        QString rejected;
        QObject::connect(model, &LocoFieldModel::editRejected, [&rejected](const QString &why) { rejected = why; });
        const int wheelRow = model->rowForKey(QStringLiteral("loco_wheel_dia1"));
        CHECK(!model->setData(model->index(wheelRow, LocoFieldModel::ColumnValue), QStringLiteral("70000"), Qt::EditRole),
              "a u16 of 70000 is not accepted");
        CHECK(rejected.contains(QStringLiteral("0–65535")), "and the reason names the range");
        CHECK(model->values().value(QStringLiteral("loco_wheel_dia1")).toLongLong() == 950, "the value stays 950");

        const int nmsRow = model->rowForKey(QStringLiteral("nms_ip_address"));
        CHECK(model->setData(model->index(nmsRow, LocoFieldModel::ColumnValue), QStringLiteral("10.20.30.40"), Qt::EditRole),
              "the NMS address is entered dotted");

        window.setTarget(QStringLiteral("not-an-ip"), vcc.localPort());
        CHECK(!window.sendBlocker().isEmpty(), "a bad target IP blocks sending");
        window.setTarget(QStringLiteral("127.0.0.1"), vcc.localPort());
        CHECK(window.sendBlocker().isEmpty(), "a good one does not");

        sentBody = window.currentBody();
        CHECK(window.sendNow(false), "sent");

        QElapsedTimer clock;
        clock.start();
        while (!vcc.hasPendingDatagrams() && clock.elapsed() < 3000) {
            QCoreApplication::processEvents(QEventLoop::AllEvents, 50);
        }
        QByteArray datagram;
        datagram.resize(static_cast<int>(vcc.pendingDatagramSize()));
        vcc.readDatagram(datagram.data(), datagram.size());
        CHECK(datagram == LocoInfo::message(sentBody), "the VCC receives exactly header + body");

        LocoInfo::Layout layout;
        QString error;
        layout.load(QStringLiteral(":/schema/kavach.xml"), &error);
        const LocoInfo::Parsed received = LocoInfo::parseBody(layout, datagram);
        CHECK(received.ok && received.crcOk, "with a good loco_info_crc");
        CHECK(received.values.value(QStringLiteral("loco_unit_id")).toLongLong() == 30421
                  && received.values.value(QStringLiteral("nms_ip_address")).toLongLong() == 0x0A141E28,
              "carrying the edits (10.20.30.40 stored the way the tool stores addresses)");

        const QList<LocoInfo::SendRecord> history = LocoInfo::SendHistory(window.historyPath()).readAll();
        CHECK(history.size() == 1 && history.first().body == sentBody, "the send is in the history, byte for byte");
        CHECK(!model->index(unitRow, 0).data(LocoFieldModel::ChangedSinceSentRole).toBool(),
              "after sending, nothing is 'changed since last send'");

        const int shuntRow = model->rowForKey(QStringLiteral("shunt_speed"));
        model->setData(model->index(shuntRow, LocoFieldModel::ColumnValue), QStringLiteral("20"), Qt::EditRole);
        CHECK(model->index(shuntRow, 0).data(LocoFieldModel::ChangedSinceSentRole).toBool(),
              "a later edit is marked as not yet sent");
    }   // closing flushes the pending save

    {
        LocoConfigWindow reopened(nullptr, temp.path());
        LocoFieldModel *model = reopened.fieldModel();
        CHECK(model->values().value(QStringLiteral("loco_unit_id")).toLongLong() == 30421,
              "reopening keeps the edited configuration");
        CHECK(model->values().value(QStringLiteral("shunt_speed")).toLongLong() == 20, "including the unsent edit");
        CHECK(model->index(model->rowForKey(QStringLiteral("shunt_speed")), 0)
                  .data(LocoFieldModel::ChangedSinceSentRole).toBool(),
              "which is still marked as not sent — judged against the stored bytes");
        CHECK(!model->index(model->rowForKey(QStringLiteral("loco_unit_id")), 0)
                   .data(LocoFieldModel::ChangedSinceSentRole).toBool(),
              "while the sent one is not");
    }

    // ---- bulk send: the same bytes to three VCCs, recorded per target ------------
    {
        QUdpSocket second;
        QUdpSocket third;
        CHECK(second.bind(QHostAddress(QHostAddress::LocalHost), 0) && third.bind(QHostAddress(QHostAddress::LocalHost), 0),
              "two more stand-in VCCs");
        LocoConfigWindow window(nullptr, temp.path());
        QVector<LocoInfo::SendTarget> targets(LocoInfo::kMaxTargets);
        targets[0].ip = QStringLiteral("127.0.0.1");
        targets[0].port = vcc.localPort();
        targets[1].ip = QStringLiteral("127.0.0.1");
        targets[1].port = second.localPort();
        targets[2].ip = QStringLiteral("127.0.0.1");
        targets[2].port = third.localPort();
        targets[3].ip = QStringLiteral("junk");
        targets[3].enabled = false;          // unticked: ignored
        window.setTargets(targets);
        CHECK(window.sendBlocker().isEmpty(), "three good targets and an unticked junk row can be sent");
        const QPushButton *sendButton = nullptr;
        for (QPushButton *button : window.findChildren<QPushButton *>()) {
            if (button->text().startsWith(QStringLiteral("Send to"))) {
                sendButton = button;
            }
        }
        CHECK(sendButton && sendButton->text() == QStringLiteral("Send to 3 VCCs…"), "the button says how many");

        const int historyBefore = LocoInfo::SendHistory(window.historyPath()).readAll().size();
        const QByteArray body = window.currentBody();
        CHECK(window.sendNow(false), "bulk send");
        QElapsedTimer clock;
        clock.start();
        while ((!vcc.hasPendingDatagrams() || !second.hasPendingDatagrams() || !third.hasPendingDatagrams())
               && clock.elapsed() < 3000) {
            QCoreApplication::processEvents(QEventLoop::AllEvents, 50);
        }
        auto take = [](QUdpSocket &socket) {
            QByteArray datagram;
            datagram.resize(static_cast<int>(socket.pendingDatagramSize()));
            socket.readDatagram(datagram.data(), datagram.size());
            return datagram;
        };
        const QByteArray expected = LocoInfo::message(body);
        CHECK(take(vcc) == expected && take(second) == expected && take(third) == expected,
              "all three receive exactly the same datagram");

        const QList<LocoInfo::SendRecord> history = LocoInfo::SendHistory(window.historyPath()).readAll();
        CHECK(history.size() == historyBefore + 3, "one history record per target");
        QStringList recordedTargets;
        for (int index = historyBefore; index < history.size(); ++index) {
            recordedTargets.append(history.at(index).target);
        }
        CHECK(recordedTargets.contains(QStringLiteral("127.0.0.1:%1").arg(second.localPort()))
                  && recordedTargets.contains(QStringLiteral("127.0.0.1:%1").arg(third.localPort())),
              "each naming its own target");

        targets[1].port = targets[0].port;   // the same VCC twice
        window.setTargets(targets);
        CHECK(window.sendBlocker().contains(QStringLiteral("twice")), "the same target twice blocks sending");
        window.setTarget(QStringLiteral("127.0.0.1"), vcc.localPort());   // back to a single target
    }
}
