#!/usr/bin/env python3
"""Build DLConsole's station layout library (session 211).

    scripts/station_layout_library.py <loco_performance/config/station> station_layouts --qrc station_layouts.qrc

Copies every station file of the old Python tool (DEBUGGING_TOOL_KAVACH)
into <out>, keeping its folders (ajay/, sOs_adj/, Originals/) and leaving
out the circuits sheets, "(copy)" files and "New Folder". Names are made
Windows-safe (anything but letters, digits, . _ + - becomes _). Files are
copied byte for byte. Then writes the .qrc listing them. station.xlsx at the
top is the default layout (Tools > Station Layout opens it with no last
file). Standard library only.
"""
import argparse, os, re, shutil, zipfile

def safe(name):
    return re.sub(r"_+", "_", re.sub(r"[^A-Za-z0-9._+-]", "_", name)).strip("_")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("out")
    ap.add_argument("--qrc", required=True)
    a = ap.parse_args()
    files = []
    for root, dirs, names in os.walk(a.src):
        dirs[:] = sorted(d for d in dirs if d != "New Folder")
        rel = os.path.relpath(root, a.src)
        for n in sorted(names):
            if not n.endswith(".xlsx") or n.startswith("circuits") or "(copy)" in n or n.startswith("~$"):
                continue
            src = os.path.join(root, n)
            try:
                if "xl/workbook.xml" not in zipfile.ZipFile(src).namelist() or \
                   'name="tags"' not in zipfile.ZipFile(src).read("xl/workbook.xml").decode("utf-8", "replace"):
                    print("skipped (no tags sheet):", src); continue
            except zipfile.BadZipFile:
                print("skipped (not a zip):", src); continue
            sub = "" if rel == "." else safe(rel)
            dst_rel = os.path.join(sub, safe(n)) if sub else safe(n)
            dst = os.path.join(a.out, dst_rel)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(src, dst)
            files.append(os.path.join(os.path.basename(os.path.normpath(a.out)), dst_rel).replace(os.sep, "/"))
    with open(a.qrc, "w") as q:
        q.write("<!-- Generated by scripts/station_layout_library.py: the built-in station layouts\n"
                "     (the old Python tool's config/station/*.xlsx, unchanged). station.xlsx at the\n"
                "     top is the default layout. -->\n<RCC>\n    <qresource prefix=\"/\">\n")
        for f in sorted(files):
            q.write("        <file>%s</file>\n" % f)
        q.write("    </qresource>\n</RCC>\n")
    print(len(files), "station files")

if __name__ == "__main__":
    main()
