#!/usr/bin/env python3
"""Turn tags_sim's KAV_CONFIG folder into a DLConsole tag scenario library.

    python3 scripts/tags_sim_library.py KAV_CONFIG OUT_DIR [--qrc FILE.qrc]

OUT_DIR gets the same folder tree with:
  - every .xlsx route converted to .tagroute.xml (tags AND signals), its
    direction taken from its first two locations that differ, as tags_sim
    took it (rising = nominal, dir 1);
  - every .xml that holds tags (route.xml, Configuration1.xml) copied as it is;
  - nothing else (tags_sim's .txt exports, vdu files with no tags, scripts,
    office lock files).
File and folder names lose the characters Windows forbids (<>:"|?*).

With --qrc, also writes a Qt resource file listing OUT_DIR's files under the
prefix /, for building the library into DLConsole (session 201). Standard
library only, like tags_sim_import.py, whose conversion it reuses.
"""
import os
import re
import shutil
import sys
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tags_sim_import  # noqa: E402

FORBIDDEN = re.compile(r'[<>:"|?*]')


def safe(name):
    return FORBIDDEN.sub('', name.replace('->', '-'))


def abs_loc(page_x):
    return (int(page_x, 16) >> 16) & ((1 << 23) - 1)


def infer_dir(path):
    root = ET.parse(path).getroot()
    locs = [abs_loc(t.get('page_x')) for t in root.findall('tag')]
    for a, b in zip(locs, locs[1:]):
        if a != b:
            root.set('dir', '1' if b > a else '2')
            break
    ET.ElementTree(root).write(path, encoding='UTF-8', xml_declaration=True)


def holds_tags(path):
    try:
        return any(e.get('page_x') for e in ET.parse(path).getroot().iter('rfid_data'))
    except ET.ParseError:
        return False


def main(src, out, qrc):
    made, copied, skipped = 0, 0, []
    for folder, dirs, files in os.walk(src):
        dirs.sort()
        rel = os.path.relpath(folder, src)
        dest = os.path.join(out, *[safe(p) for p in rel.split(os.sep) if p != '.'])
        for f in sorted(files):
            path = os.path.join(folder, f)
            if f.startswith(('.~lock', '~$')):
                continue
            if f.lower().endswith('.xlsx'):
                os.makedirs(dest, exist_ok=True)
                tmp = os.path.join(dest, safe(f))
                shutil.copyfile(path, tmp)
                try:
                    converted, _ = tags_sim_import.convert(tmp)
                    infer_dir(converted)
                    made += 1
                except Exception as e:  # keep going through the folder
                    skipped.append('%s (%s)' % (os.path.join(rel, f), e))
                finally:
                    os.remove(tmp)
            elif f.lower().endswith('.xml') and holds_tags(path):
                os.makedirs(dest, exist_ok=True)
                shutil.copyfile(path, os.path.join(dest, safe(f)))
                copied += 1
    print('%d xlsx routes converted, %d xml files copied into %s' % (made, copied, out))
    for s in skipped:
        print('  not converted: ' + s, file=sys.stderr)
    if qrc:
        base = os.path.dirname(os.path.abspath(qrc))
        names = []
        for folder, dirs, files in os.walk(out):
            dirs.sort()
            for f in sorted(files):
                names.append(os.path.relpath(os.path.join(folder, f), base).replace(os.sep, '/'))
        with open(qrc, 'w', encoding='utf-8') as q:
            q.write('<!-- Generated by scripts/tags_sim_library.py: the built-in tag scenario library. -->\n')
            q.write('<RCC>\n    <qresource prefix="/">\n')
            for n in names:
                q.write('        <file>%s</file>\n' % n)
            q.write('    </qresource>\n</RCC>\n')
        print('%s: %d files' % (qrc, len(names)))
    return 1 if skipped else 0


if __name__ == '__main__':
    args = sys.argv[1:]
    qrc = None
    if '--qrc' in args:
        i = args.index('--qrc')
        qrc = args[i + 1]
        del args[i:i + 2]
    if len(args) != 2:
        sys.exit(__doc__)
    sys.exit(main(args[0], args[1], qrc))
